openapi: "3.0.0"
info:
  version: 1.0.0
  title: Simple sponsorship api
  license:
    name: MIT
servers:
  - url: https://lively-wildflower-6281.getsandbox.com/
paths:
  /players:
    get:
      summary: List all players
      operationId: getPlayers
      tags:
        - Players
      parameters:
        - name: id
          in: query
          description: id of specific player
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '201':
          description: Array of players
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Players"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Add new player
      operationId: addPlayer
      tags:
        - Players
      responses:
        '201':
          description: Registers new player in memory          
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Players"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Remove all players
      operationId: removePlayers
      tags:
        - Players
      responses:
        '200':
          description: OK
  /sponsorships:
    post:
      summary: Record new sponsorship
      operationId: addSponsorship
      tags:
        - Sponsorships
      responses:
        '201':
          description: Registers new sponsorship in memory
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Sponsorship"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sponsorship"
components:
  schemas:
    Player:
      type: object
      required:
        - nickname
      properties:
        id:
          type: integer
          format: int64
        nickname:
          type: string
        balance:
          type: number
          format: double
        canLend:
           type: boolean
        canBorrow:
           type: boolean
    Sponsorship:
      type: object
      required:
        - creditorId
        - recepientId
        - amount
      properties:
        id:
          type: integer
          format: int64
        creditorId:
          type: integer
          format: int64
        recepientId:
          type: integer
          format: int64
        amount:
          type: number
          format: double
        isPaidOff:
           type: boolean
    Players:
      type: array
      items:
        $ref: "#/components/schemas/Player"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string